// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(any(feature = "v0_1_18", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v0_1_18")))]
use crate::CandidateTransport;
use crate::CandidateType;
use glib::translate::*;

glib::glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Candidate(Boxed<ffi::NiceCandidate>);

    match fn {
        copy => |ptr| ffi::nice_candidate_copy(mut_override(ptr)),
        free => |ptr| ffi::nice_candidate_free(ptr),
        get_type => || ffi::nice_candidate_get_type(),
    }
}

impl Candidate {
    #[doc(alias = "nice_candidate_new")]
    pub fn new(type_: CandidateType) -> Candidate {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::nice_candidate_new(type_.to_glib()))
        }
    }

    #[cfg(any(feature = "v0_1_15", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v0_1_15")))]
    #[doc(alias = "nice_candidate_equal_target")]
    pub fn equal_target(&self, candidate2: &Candidate) -> bool {
        unsafe {
            from_glib(ffi::nice_candidate_equal_target(self.to_glib_none().0, candidate2.to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v0_1_18", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v0_1_18")))]
    #[doc(alias = "nice_candidate_transport_to_string")]
    pub fn transport_to_string(transport: CandidateTransport) -> Option<glib::GString> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::nice_candidate_transport_to_string(transport.to_glib()))
        }
    }

    #[cfg(any(feature = "v0_1_18", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v0_1_18")))]
    #[doc(alias = "nice_candidate_type_to_string")]
    pub fn type_to_string(type_: CandidateType) -> Option<glib::GString> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::nice_candidate_type_to_string(type_.to_glib()))
        }
    }
}
