// This file was generated by gir (https://github.com/gtk-rs/gir @ 6ec2baf)
// from gir-files (https://github.com/gtk-rs/gir-files @ 998d8b1)
// DO NOT EDIT

use std::env;
use std::error::Error;
use std::path::Path;
use std::mem::{align_of, size_of};
use std::process::Command;
use std::str;
use tempfile::Builder;
use nice_sys::*;

static PACKAGES: &[&str] = &["nice"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Compiler, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Compiler { args })
    }

    pub fn define<'a, V: Into<Option<&'a str>>>(&mut self, var: &str, val: V) {
        let arg = match val.into() {
            None => format!("-D{}", var),
            Some(val) => format!("-D{}={}", var, val),
        };
        self.args.push(arg);
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {:?} failed, {}",
                               &cmd, status).into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{} {}", name, err).into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let mut cmd = Command::new("pkg-config");
    cmd.arg("--cflags");
    cmd.args(packages);
    let out = cmd.output()?;
    if !out.status.success() {
        return Err(format!("command {:?} returned {}",
                           &cmd, out.status).into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}


#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
    /// Number of tests that failed to compile.
    failed_to_compile: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn record_failed_to_compile(&mut self) {
        self.failed += 1;
        self.failed_to_compile += 1;
    }
    fn summary(&self) -> String {
        format!(
            "{} passed; {} failed (compilation errors: {})",
            self.passed,
            self.failed,
            self.failed_to_compile)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let tmpdir = Builder::new().prefix("abi").tempdir().expect("temporary directory");
    let cc = Compiler::new().expect("configured compiler");

    assert_eq!("1",
               get_c_value(tmpdir.path(), &cc, "1").expect("C constant"),
               "failed to obtain correct constant value for 1");

    let mut results : Results = Default::default();
    for (i, &(name, rust_value)) in RUST_CONSTANTS.iter().enumerate() {
        match get_c_value(tmpdir.path(), &cc, name) {
            Err(e) => {
                results.record_failed_to_compile();
                eprintln!("{}", e);
            },
            Ok(ref c_value) => {
                if rust_value == c_value {
                    results.record_passed();
                } else {
                    results.record_failed();
                    eprintln!("Constant value mismatch for {}\nRust: {:?}\nC:    {:?}",
                              name, rust_value, c_value);
                }
            }
        };
        if (i + 1) % 25 == 0 {
            println!("constants ... {}", results.summary());
        }
    }
    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let tmpdir = Builder::new().prefix("abi").tempdir().expect("temporary directory");
    let cc = Compiler::new().expect("configured compiler");

    assert_eq!(Layout {size: 1, alignment: 1},
               get_c_layout(tmpdir.path(), &cc, "char").expect("C layout"),
               "failed to obtain correct layout for char type");

    let mut results : Results = Default::default();
    for (i, &(name, rust_layout)) in RUST_LAYOUTS.iter().enumerate() {
        match get_c_layout(tmpdir.path(), &cc, name) {
            Err(e) => {
                results.record_failed_to_compile();
                eprintln!("{}", e);
            },
            Ok(c_layout) => {
                if rust_layout == c_layout {
                    results.record_passed();
                } else {
                    results.record_failed();
                    eprintln!("Layout mismatch for {}\nRust: {:?}\nC:    {:?}",
                              name, rust_layout, &c_layout);
                }
            }
        };
        if (i + 1) % 25 == 0 {
            println!("layout    ... {}", results.summary());
        }
    }
    results.expect_total_success();
}

fn get_c_layout(dir: &Path, cc: &Compiler, name: &str) -> Result<Layout, Box<dyn Error>> {
    let exe = dir.join("layout");
    let mut cc = cc.clone();
    cc.define("ABI_TYPE_NAME", name);
    cc.compile(Path::new("tests/layout.c"), &exe)?;

    let mut abi_cmd = Command::new(exe);
    let output = abi_cmd.output()?;
    if !output.status.success() {
        return Err(format!("command {:?} failed, {:?}",
                           &abi_cmd, &output).into());
    }

    let stdout = str::from_utf8(&output.stdout)?;
    let mut words = stdout.trim().split_whitespace();
    let size = words.next().unwrap().parse().unwrap();
    let alignment = words.next().unwrap().parse().unwrap();
    Ok(Layout {size, alignment})
}

fn get_c_value(dir: &Path, cc: &Compiler, name: &str) -> Result<String, Box<dyn Error>> {
    let exe = dir.join("constant");
    let mut cc = cc.clone();
    cc.define("ABI_CONSTANT_NAME", name);
    cc.compile(Path::new("tests/constant.c"), &exe)?;

    let mut abi_cmd = Command::new(exe);
    let output = abi_cmd.output()?;
    if !output.status.success() {
        return Err(format!("command {:?} failed, {:?}",
                           &abi_cmd, &output).into());
    }

    let output = str::from_utf8(&output.stdout)?.trim();
    if !output.starts_with("###gir test###") ||
       !output.ends_with("###gir test###") {
        return Err(format!("command {:?} return invalid output, {:?}",
                           &abi_cmd, &output).into());
    }

    Ok(String::from(&output[14..(output.len() - 14)]))
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    ("NiceAddress", Layout {size: size_of::<NiceAddress>(), alignment: align_of::<NiceAddress>()}),
    ("NiceAgentClass", Layout {size: size_of::<NiceAgentClass>(), alignment: align_of::<NiceAgentClass>()}),
    ("NiceAgentOption", Layout {size: size_of::<NiceAgentOption>(), alignment: align_of::<NiceAgentOption>()}),
    ("NiceCandidate", Layout {size: size_of::<NiceCandidate>(), alignment: align_of::<NiceCandidate>()}),
    ("NiceCandidateTransport", Layout {size: size_of::<NiceCandidateTransport>(), alignment: align_of::<NiceCandidateTransport>()}),
    ("NiceCandidateType", Layout {size: size_of::<NiceCandidateType>(), alignment: align_of::<NiceCandidateType>()}),
    ("NiceCompatibility", Layout {size: size_of::<NiceCompatibility>(), alignment: align_of::<NiceCompatibility>()}),
    ("NiceComponentState", Layout {size: size_of::<NiceComponentState>(), alignment: align_of::<NiceComponentState>()}),
    ("NiceComponentType", Layout {size: size_of::<NiceComponentType>(), alignment: align_of::<NiceComponentType>()}),
    ("NiceInputMessage", Layout {size: size_of::<NiceInputMessage>(), alignment: align_of::<NiceInputMessage>()}),
    ("NiceNominationMode", Layout {size: size_of::<NiceNominationMode>(), alignment: align_of::<NiceNominationMode>()}),
    ("NiceOutputMessage", Layout {size: size_of::<NiceOutputMessage>(), alignment: align_of::<NiceOutputMessage>()}),
    ("NiceProxyType", Layout {size: size_of::<NiceProxyType>(), alignment: align_of::<NiceProxyType>()}),
    ("NiceRelayType", Layout {size: size_of::<NiceRelayType>(), alignment: align_of::<NiceRelayType>()}),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("NICE_AGENT_MAX_REMOTE_CANDIDATES", "25"),
    ("(guint) NICE_AGENT_OPTION_ICE_TRICKLE", "8"),
    ("(guint) NICE_AGENT_OPTION_LITE_MODE", "4"),
    ("(guint) NICE_AGENT_OPTION_REGULAR_NOMINATION", "1"),
    ("(guint) NICE_AGENT_OPTION_RELIABLE", "2"),
    ("(guint) NICE_AGENT_OPTION_SUPPORT_RENOMINATION", "16"),
    ("NICE_CANDIDATE_MAX_FOUNDATION", "33"),
    ("NICE_CANDIDATE_MAX_LOCAL_ADDRESSES", "64"),
    ("NICE_CANDIDATE_MAX_TURN_SERVERS", "8"),
    ("(gint) NICE_CANDIDATE_TRANSPORT_TCP_ACTIVE", "1"),
    ("(gint) NICE_CANDIDATE_TRANSPORT_TCP_PASSIVE", "2"),
    ("(gint) NICE_CANDIDATE_TRANSPORT_TCP_SO", "3"),
    ("(gint) NICE_CANDIDATE_TRANSPORT_UDP", "0"),
    ("(gint) NICE_CANDIDATE_TYPE_HOST", "0"),
    ("(gint) NICE_CANDIDATE_TYPE_PEER_REFLEXIVE", "2"),
    ("(gint) NICE_CANDIDATE_TYPE_RELAYED", "3"),
    ("(gint) NICE_CANDIDATE_TYPE_SERVER_REFLEXIVE", "1"),
    ("(gint) NICE_COMPATIBILITY_DRAFT19", "0"),
    ("(gint) NICE_COMPATIBILITY_GOOGLE", "1"),
    ("(gint) NICE_COMPATIBILITY_LAST", "5"),
    ("(gint) NICE_COMPATIBILITY_MSN", "2"),
    ("(gint) NICE_COMPATIBILITY_OC2007", "4"),
    ("(gint) NICE_COMPATIBILITY_OC2007R2", "5"),
    ("(gint) NICE_COMPATIBILITY_RFC5245", "0"),
    ("(gint) NICE_COMPATIBILITY_WLM2009", "3"),
    ("(gint) NICE_COMPONENT_STATE_CONNECTED", "3"),
    ("(gint) NICE_COMPONENT_STATE_CONNECTING", "2"),
    ("(gint) NICE_COMPONENT_STATE_DISCONNECTED", "0"),
    ("(gint) NICE_COMPONENT_STATE_FAILED", "5"),
    ("(gint) NICE_COMPONENT_STATE_GATHERING", "1"),
    ("(gint) NICE_COMPONENT_STATE_LAST", "6"),
    ("(gint) NICE_COMPONENT_STATE_READY", "4"),
    ("(gint) NICE_COMPONENT_TYPE_RTCP", "2"),
    ("(gint) NICE_COMPONENT_TYPE_RTP", "1"),
    ("(gint) NICE_NOMINATION_MODE_AGGRESSIVE", "1"),
    ("(gint) NICE_NOMINATION_MODE_REGULAR", "0"),
    ("(gint) NICE_PROXY_TYPE_HTTP", "2"),
    ("(gint) NICE_PROXY_TYPE_LAST", "2"),
    ("(gint) NICE_PROXY_TYPE_NONE", "0"),
    ("(gint) NICE_PROXY_TYPE_SOCKS5", "1"),
    ("(gint) NICE_RELAY_TYPE_TURN_TCP", "1"),
    ("(gint) NICE_RELAY_TYPE_TURN_TLS", "2"),
    ("(gint) NICE_RELAY_TYPE_TURN_UDP", "0"),
];


