[options]
girs_directories = ["../gir-files"]
library = "Nice"
version = "0.1"
target_path = "."
min_cfg_version = "0.1"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

external_libraries = [
  "Glib",
  "GObject",
  "Gio",
]

generate = [
  "Nice.ComponentType",
  "Nice.Compatibility",
  "Nice.AgentOption",
  "Nice.RelayType",
  "Nice.CandidateType",
  "Nice.CandidateTransport",
  "Nice.NominationMode",
  "Nice.ProxyType",
  "Nice.Candidate",
]

manual = [
  "GLib.MainContext",
  "GLib.Error",
  "Gio.AsyncReadyCallback",
  "Gio.Socket",
  "Gio.Cancellable",
  "Gio.IOStream"
]

[[object]]
name = "Nice.Agent"
status = "generate"

    [[object.function]]
    name = "recv"
    # compiler error: generated Vec<u8>::uninit, required Vec::<u8>
    manual = true

    [[object.function]]
    name = "recv_nonblocking"
    # compiler error: generated Vec<u8>::uninit, required Vec::<u8>
    manual = true

    [[object.function]]
    name = "get_selected_pair"
    # expected *-ptr, found struct `NiceCandidate`
    ignore = true

    [[object.function]]
    name = "set_remote_candidates"
    # no method named `to_glib_none` found for reference `&[&candidate::Candidate]` in the current scope
    ignore = true

[[object]]
name = "Nice.ComponentState"
status = "generate"
    [[object.member]]
    name = "last"
    ignore = true

#[[object]]
#name = "Nice.Address"
#status = "generate"

